env                = "dev"
location           = "East US"
project            = "roboshop"
resource_group_name = "rg-roboshop-dev"
acr_name           = "roboshopdevacr"      # must be globally unique
aks_cluster_name   = "roboshop-dev-aks"
kubernetes_version = "1.35.1"
system_node_size   = "Standard_B2s"
system_node_count  = 2
workload_node_size = "Standard_B4ms"
workload_min_count = 2
workload_max_count = 6
domain             = "roboshop.yourdomain.com"  # change this