apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault-internal.learntechnology.shop:8200"
      path: "roboshop-dev"
      version: "v1"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
#
#apiVersion: external-secrets.io/v1
#kind: SecretStore
#metadata:
#name: vault-backend
#namespace: roboshop
#spec:
#provider:
#vault:
#server: "http://vault.learntechnology.shop:8200"
#path: "roboshop-dev"
#version: "v2"
#auth:
#tokenSecretRef:
#name: vault-token
#key: token