apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault-internal.learntechnology.shop:8200"
      path: "roboshop-dev"
      version: "v1"
      auth:
        tokenSecretRef:
          name: vault-token
          namespace: kube-system
          key: token