apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.appName }}
  namespace: roboshop
spec:
  provider:
    vault:
      server: "http://vault-internal.learntechnology.shop:8200"
      path: "roboshop-{{ .Values.env }}"
      version: "v1"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: roboshop
type: Opaque
stringData:
  token: <YOUR_VAULT_TOKEN>